ionic plugin add org.apache.cordova.device
ionic plugin add org.apache.cordova.inappbrowser
ionic plugin add org.apache.cordova.file
ionic plugin add org.apache.cordova.file-transfer
ionic plugin add org.apache.cordova.camera
ionic plugin add https://github.com/phonegap-build/PushPlugin.git
ionic plugin add de.appplant.cordova.plugin.local-notification
ionic plugin add https://github.com/VersoSolutions/CordovaClipboard
ionic plugin add org.apache.cordova.statusbar
ionic plugin add https://github.com/danwilson/google-analytics-plugin.git
ionic plugin add https://github.com/wymsee/cordova-imagePicker.git