ionic plugin rm org.apache.cordova.file-transfer
ionic plugin rm org.apache.cordova.camera
ionic plugin rm org.apache.cordova.file
ionic plugin rm org.apache.cordova.inappbrowser
ionic plugin rm org.apache.cordova.device
ionic plugin rm https://github.com/phonegap-build/PushPlugin.git
ionic plugin rm de.appplant.cordova.plugin.local-notification
ionic plugin rm https://github.com/VersoSolutions/CordovaClipboard
ionic plugin rm org.apache.cordova.statusbar
ionic plugin rm https://github.com/danwilson/google-analytics-plugin.git
ionic plugin rm https://github.com/wymsee/cordova-imagePicker.git
ionic plugin rm org.apache.cordova.geolocation
ionic plugin rm com.ionic.keyboard
ionic plugin rm io.litehelpers.cordova.sqlite